##########################################################################################
# Load packages
library(phyloseq)
library(tidyverse)
library(readxl)

## Use the count data generated by metaphlan4
# Read the count data and taxonomy assignment table
outdir <- "/fs/ess/PAS3107/menuka/results"
count_file <- "/fs/ess/PAS3107/metaG/stats/metaphlan4_merged_read_counts_sp_only_sort.txt"
counts <- read.table(count_file,
                     sep="",  header=TRUE, 
                     row.names=1, check.names=FALSE)

count_matrix <- as.matrix(counts)
head(count_matrix)
colSums(count_matrix)
count_matrix_nc_rem <- count_matrix[, -1]
colSums(count_matrix_nc_rem)

# Build phyloseq object
# Row names of count matrix must match row names of taxonomy
# create count table
ps_count <- otu_table(count_matrix_nc_rem, taxa_are_rows = TRUE)

# create taxonomy table
Tax <- tax_table(matrix(rownames(count_matrix_nc_rem), ncol = 1,
                        dimnames = list(rownames(count_matrix_nc_rem), "Species")))

## Read sample_data - sample name must matches the column name of the count table
sample_sheet <- read_excel("/fs/ess/PAS3107/menuka/data/sample_data_read.xlsx")
str(sample_sheet)

# Convert tibble to dataframe
meta <- data.frame(sample_sheet)
rownames(meta) <- meta$Sample
meta$Sample <- NULL
meta_data <- sample_data(meta)
meta_data_nc_rem <- meta_data[-12, drop = FALSE]

## Make sure that rownames of metadata matches the sample/column name in count tables
all(colnames(count_matrix_nc_rem) %in% rownames(meta_data_nc_rem))

## Create phyloseq object
ps <- phyloseq(ps_count, Tax, meta_data_nc_rem)

## Save phyloseq object
saveRDS(ps, 
        file = file.path(outdir, "seqtab_countdata_reads.rds"))

outdir <- "/fs/ess/PAS3107/menuka/results"
## read phyloseq obejct to compute alpha diversity
ps <- readRDS(file.path(outdir, "seqtab_countdata_reads.rds"))
ps
## Alpha diversity
alpha_diversity <- estimate_richness(ps)

## Groups to compare - First separate RVA vs RVC, in RVA compare between positive and negative
## First check the distribution of data and apply stats.
rownames(alpha_diversity) <- sub("^[^_]+_([A-Z]\\d{2}).*", "\\1", rownames(alpha_diversity))
alpha_diversity_merge <- rownames_to_column(alpha_diversity, var = "SampleID")
## Merge the metadata and alpha diversity now
metadata <- read_excel("../data/MetaG_metadata_stephanie.xlsx")
alpha_diversity_merged <- left_join(alpha_diversity_merge, metadata, by = "SampleID")

## Filter RVA dataset
RVA_dataset <- alpha_diversity_merged |> 
  filter(RV_Type == "RVA")

shapiro.test(RVA_dataset$Observed)
## P-value > 0.05 data is normal, normal data apply t-test and for not-normal data apply kruskal wallis
t.test(Observed ~ Paired_Nasal_RV_Status, data = RVA_dataset)

kruskal.test(RVA_dataset$Paired_Nasal_RV_Status ~ RVA_dataset$Observed)


## Beta diversity
do <- ordinate(ps, method = "PCoA", distance = "bray")

plot_ordination(ps, do) +
  geom_point(size=3)

